### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by GrantRVD** [GrantRVD/data-neuroscience#1]
A Roadmap for the data-neuroscience

# Resource Collection and Organization
- [ ] Decide on the sub-domains of neuroscience the syllabus should represent.
- [ ] Organize the above subdomains into `modules`
- [ ] Select at least 5 `resources` (i.e published open-access manuscript w/ freely available data) per module
- [ ] Annotate all resources in a formatted file (e.g. JSON)

# Distribution
- [ ] Establish a web page explaining the aim of The Data Neuroscientist
- [ ] List and hyperlink all resources on The Data Neuroscientist webpage (Github Page)
- [ ] Create a basic tool for downloading all or part of the compiled documents

# Extension of Resources
- [ ] Create tutorials or how-tos for resources that have more opaque documentation
- [ ] Host executable notebooks on [binder](mybinder.org) where appropriate
- [ ] Link executable notebooks to web page
